# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-10 18:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('horse_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('info', models.TextField()),
                ('pic', models.ImageField(blank=True, null=True, upload_to='bookmaking/media')),
                ('ratio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Jockey',
            fields=[
                ('jockey_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('ratio', models.FloatField()),
                ('contacts', models.CharField(max_length=50)),
                ('review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('ride_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('horse', models.ManyToManyField(blank=True, null=True, to='bookmaking.Horse')),
            ],
        ),
        migrations.CreateModel(
            name='Stake',
            fields=[
                ('stake_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.FloatField()),
                ('horse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookmaking.Horse')),
            ],
        ),
        migrations.CreateModel(
            name='User1',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='users', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='bookmaking/media')),
                ('contacts', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='stake',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horse',
            name='jockey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookmaking.Jockey'),
        ),
        migrations.AddField(
            model_name='horse',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to='bookmaking.User1'),
        ),
    ]
