# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-11 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmaking', '0002_remove_horse_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
