# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-11 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmaking', '0004_auto_20161211_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
